#!/usr/bin/env node
/**
 * Inline the map engines into the app:
 *   the Territory Network   src/features/world/engine/engine.js + engine.css (+ the logo)
 *   the IISER Kolkata map   src/features/campus/engine/campusEngine.js + campusEngine.css
 *
 *   node scripts/world-engine.mjs           write each engine's engineSource.generated.ts
 *   node scripts/world-engine.mjs --check   fail if a generated file is out of date (npm test runs this)
 *
 * An engine runs inside a WebView / iframe, not in the app's JS runtime, so it has to reach the
 * page as text. Hermes can't turn a function back into source, so the app can't stringify it at
 * runtime either — hence this step. Edit the .js / .css, then run it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const TARGETS = [
  {
    dir: 'src/features/world/engine',
    render(dir) {
      const js = readFileSync(join(dir, 'engine.js'), 'utf8');
      const css = readFileSync(join(dir, 'engine.css'), 'utf8');
      const logo = readFileSync(join(root, 'assets/brand/logo-marker.png')).toString('base64');
      return [
        '// GENERATED by scripts/world-engine.mjs from engine.js, engine.css and assets/brand/logo-marker.png.',
        '// Do not edit: change the sources and run `node scripts/world-engine.mjs`.',
        `export const ENGINE_JS = ${JSON.stringify(js)};`,
        `export const ENGINE_CSS = ${JSON.stringify(css)};`,
        `export const LOGO_DATA_URL = ${JSON.stringify(`data:image/png;base64,${logo}`)};`,
        '',
      ].join('\n');
    },
  },
  {
    dir: 'src/features/campus/engine',
    render(dir) {
      const js = readFileSync(join(dir, 'campusEngine.js'), 'utf8');
      const css = readFileSync(join(dir, 'campusEngine.css'), 'utf8');
      return [
        '// GENERATED by scripts/world-engine.mjs from campusEngine.js and campusEngine.css.',
        '// Do not edit: change the sources and run `node scripts/world-engine.mjs`.',
        `export const CAMPUS_ENGINE_JS = ${JSON.stringify(js)};`,
        `export const CAMPUS_ENGINE_CSS = ${JSON.stringify(css)};`,
        '',
      ].join('\n');
    },
  },
];

/** The Territory Network's generated source (kept for scripts that import it). */
export function render() {
  return TARGETS[0].render(join(root, TARGETS[0].dir));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  for (const t of TARGETS) {
    const dir = join(root, t.dir);
    const out = join(dir, 'engineSource.generated.ts');
    const next = t.render(dir);
    if (check) {
      let cur = '';
      try {
        cur = readFileSync(out, 'utf8');
      } catch {}
      if (cur !== next) {
        console.error(`${t.dir}/engineSource.generated.ts is out of date: run \`node scripts/world-engine.mjs\``);
        process.exit(1);
      }
    } else {
      writeFileSync(out, next);
      console.log(`wrote ${out} (${Math.round(next.length / 1024)} KB)`);
    }
  }
  if (check) console.log('engine sources are up to date');
}
