#!/usr/bin/env node
/**
 * Inline the Territory Network's map engine into the app.
 *
 *   node scripts/world-engine.mjs           write src/features/world/engine/engineSource.generated.ts
 *   node scripts/world-engine.mjs --check   fail if the generated file is out of date (npm test runs this)
 *
 * The engine (engine.js + engine.css) runs inside a WebView / iframe, not in the app's JS runtime,
 * so it has to reach the page as text. Hermes can't turn a function back into source, so the app
 * can't stringify it at runtime either — hence this step. Edit engine.js / engine.css, then run it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'src/features/world/engine');
const OUT = join(dir, 'engineSource.generated.ts');

export function render() {
  const js = readFileSync(join(dir, 'engine.js'), 'utf8');
  const css = readFileSync(join(dir, 'engine.css'), 'utf8');
  const logo = readFileSync(join(root, 'assets/brand/logo-marker.png')).toString('base64');
  return [
    '// GENERATED by scripts/world-engine.mjs from engine.js, engine.css and assets/brand/logo-marker.png.',
    '// Do not edit: change the sources and run `node scripts/world-engine.mjs`.',
    `export const ENGINE_JS = ${JSON.stringify(js)};`,
    `export const ENGINE_CSS = ${JSON.stringify(css)};`,
    `export const LOGO_DATA_URL = ${JSON.stringify(`data:image/png;base64,${logo}`)};`,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render();
  if (process.argv.includes('--check')) {
    const cur = readFileSync(OUT, 'utf8');
    if (cur !== next) {
      console.error('engineSource.generated.ts is out of date: run `node scripts/world-engine.mjs`');
      process.exit(1);
    }
    console.log('engine source is up to date');
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT} (${Math.round(next.length / 1024)} KB)`);
  }
}
