"""initial progress and challenges schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 11:30:40.798076
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('campus', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_campus'), 'users', ['campus'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_activity_user_idem')
    )
    op.create_index('ix_activity_user_date', 'activity_events', ['user_id', 'local_date'], unique=False)
    op.create_index('ix_activity_user_type_time', 'activity_events', ['user_id', 'type', 'occurred_at'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=24), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('xp_reward_tie', sa.Integer(), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('winner_user_id', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("kind in ('daily','head_to_head','group','special')", name='ck_challenge_kind'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_challenge_window'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'local_date', name='uq_challenge_daily_template')
    )
    op.create_index('ix_challenge_kind_window', 'challenges', ['kind', 'starts_at', 'ends_at'], unique=False)
    op.create_index('ix_challenge_status_end', 'challenges', ['status', 'ends_at'], unique=False)
    op.create_table('daily_progress',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('workouts', sa.Integer(), nullable=False),
    sa.Column('workout_minutes', sa.Float(), nullable=False),
    sa.Column('active_minutes', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('challenges_completed', sa.Integer(), nullable=False),
    sa.Column('goals_completed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date')
    )
    op.create_index('ix_daily_date_xp', 'daily_progress', ['local_date', 'xp'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.String(length=64), nullable=False),
    sa.Column('followee_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='ck_follows_not_self'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_index('ix_follows_followee', 'follows', ['followee_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('total_xp', sa.BigInteger(), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_workout_minutes', sa.Float(), nullable=False),
    sa.Column('total_active_minutes', sa.Float(), nullable=False),
    sa.Column('total_steps', sa.BigInteger(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.BigInteger(), nullable=False),
    sa.Column('challenges_completed', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_stats_total_xp', 'user_stats', ['total_xp'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_xp_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'source_id', name='uq_xp_award_once')
    )
    op.create_index('ix_xp_date_user', 'xp_transactions', ['local_date', 'user_id'], unique=False)
    op.create_index('ix_xp_user_created', 'xp_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('challenge_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_participant_once')
    )
    op.create_index('ix_participant_challenge_progress', 'challenge_participants', ['challenge_id', 'progress'], unique=False)
    op.create_index('ix_participant_user_status', 'challenge_participants', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participant_user_status', table_name='challenge_participants')
    op.drop_index('ix_participant_challenge_progress', table_name='challenge_participants')
    op.drop_table('challenge_participants')
    op.drop_index('ix_xp_user_created', table_name='xp_transactions')
    op.drop_index('ix_xp_date_user', table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index('ix_stats_total_xp', table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index('ix_follows_followee', table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_daily_date_xp', table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index('ix_challenge_status_end', table_name='challenges')
    op.drop_index('ix_challenge_kind_window', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_activity_user_type_time', table_name='activity_events')
    op.drop_index('ix_activity_user_date', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_users_campus'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
